name: Sync DNS

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Use --force flag"
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3"
          cache: "pip" # caches pip dependencies
      - name: Install OctoDNS
        run: pip install 'octodns==0.9.10'
      - name: Sync w/ production DNS providers
        run: ./bin/sync ${{ inputs.force && '--force' || '' }}
        env:
          HETZNER_KEY: ${{ secrets.HETZNER_KEY }}
