name: Dry Run DNS

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      force:
        description: "Use --force flag"
        required: false
        type: boolean
        default: false

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3"
          cache: "pip" # caches pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Do a dry run
        run: ./bin/dry-run ${{ inputs.force && '--force' || '' }}
        env:
          HETZNER_KEY: ${{ secrets.HETZNER_KEY }}
